---
apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app
  namespace: istio-system
spec:
  type: LoadBalancer
  externalIPs:
  - 172.17.0.160
  ports:
  - port: 4040
    protocol: TCP
    name: http
  selector:
    app: weave-scope-app